import { createHash } from "node:crypto";
import { DatabaseSync, type SQLInputValue } from "node:sqlite";
import { beforeEach, describe, expect, it } from "vitest";
import type { SqliteExecutor } from "@/infrastructure/database/sqlite/sqlite-executor";
import { FreshDatabaseBootstrap } from "@/infrastructure/database/sqlite/migrations/fresh-database-bootstrap";
import { ImportMcqCorpus } from "@/application/mcq/import-mcq-corpus";
import { parseMcqCorpus } from "@/application/mcq/mcq-corpus-contract";
import { validCorpus } from "@/application/mcq/mcq-corpus-contract.test";
import { SqliteMcqCorpusWriter } from "./sqlite-mcq-corpus-writer";

describe("SqliteMcqCorpusWriter", () => { let sqlite: DatabaseSync; let db: SqliteExecutor; let service: ImportMcqCorpus;
  beforeEach(() => { sqlite = new DatabaseSync(":memory:"); db = { all: <T>(sql: string, ...params: SQLInputValue[]) => sqlite.prepare(sql).all(...params) as T[], run: (sql: string, ...params: SQLInputValue[]) => sqlite.prepare(sql).run(...params) }; new FreshDatabaseBootstrap(db).run(); sqlite.exec("PRAGMA foreign_keys=ON"); sqlite.prepare("INSERT INTO documents(name,type) VALUES('Source','PDF')").run(); sqlite.prepare("INSERT INTO sources(source_id,storage_id,document_id,original_filename,display_name,media_type,extension,size_bytes,checksum,status,extraction_status,version,provenance_type) VALUES('source','storage',1,'source.pdf','Source','application/pdf','pdf',1,'hash','READY','COMPLETED',1,'OFFICIAL_SOURCE')").run(); sqlite.prepare("INSERT INTO source_versions(source_version_id,source_id,version,checksum,extracted_content,extraction_status) VALUES('00000000-0000-4000-8000-000000000001','source',1,'hash','Contenu','COMPLETED')").run(); service = new ImportMcqCorpus(new SqliteMcqCorpusWriter(db), { checksum: value => createHash("sha256").update(value).digest("hex") }, { now: () => "2026-08-19T00:00:00.000Z" }); });
  it("imports atomically and is idempotent", async () => { const corpus = parseMcqCorpus(validCorpus()); await expect(service.execute(corpus)).resolves.toEqual({ created: 1, unchanged: 0 }); await expect(service.execute(corpus)).resolves.toEqual({ created: 0, unchanged: 1 }); expect(sqlite.prepare("SELECT editorial_status,source_version_id FROM mcq_item_editorial_metadata").get()).toEqual({ editorial_status: "PUBLISHED", source_version_id: "00000000-0000-4000-8000-000000000001" }); });
  it("refuses rewriting an existing version", async () => { const corpus = parseMcqCorpus(validCorpus()); await service.execute(corpus); await expect(service.execute({ ...corpus, items: [{ ...corpus.items[0]!, explanation: "Contenu différent" }] })).rejects.toMatchObject({ code: "MCQ_ITEM_VERSION_CONFLICT" }); expect(sqlite.prepare("SELECT explanation FROM mcq_question_versions").get()).toEqual({ explanation: "Justification validée" }); });
  it("does not let a checksum collision bypass immutability", async () => { const corpus = parseMcqCorpus(validCorpus()); await service.execute(corpus); const colliding = new ImportMcqCorpus(new SqliteMcqCorpusWriter(db), { checksum: () => sqlite.prepare("SELECT content_checksum FROM mcq_item_editorial_metadata").get()!.content_checksum as string }, { now: () => "later" }); await expect(colliding.execute({ ...corpus, items: [{ ...corpus.items[0]!, explanation: "Contenu différent" }] })).rejects.toMatchObject({ code: "MCQ_ITEM_VERSION_CONFLICT" }); });
  it("rolls back the complete batch when a later source is missing", async () => { const corpus = parseMcqCorpus(validCorpus()); const first = corpus.items[0]!; await expect(service.execute({ ...corpus, items: [first, { ...first, itemId: "item-2", source: { ...first.source, sourceVersionId: "missing-source" } }] })).rejects.toMatchObject({ code: "MCQ_SOURCE_VERSION_NOT_FOUND" }); expect(sqlite.prepare("SELECT COUNT(*) AS count FROM mcq_question_items").get()).toEqual({ count: 0 }); expect(sqlite.prepare("SELECT COUNT(*) AS count FROM mcq_item_editorial_metadata").get()).toEqual({ count: 0 }); });
  it("enforces the source version foreign key independently of the service guard", () => { sqlite.exec("PRAGMA foreign_keys=ON"); sqlite.prepare("INSERT INTO mcq_question_items(item_id,latest_version) VALUES('fk-item',1)").run(); sqlite.prepare("INSERT INTO mcq_question_versions(item_id,version,stem,choices_json,correct_choice_id,explanation,difficulty) VALUES('fk-item',1,'Stem','[]','a','Explanation','FOUNDATION')").run(); expect(() => sqlite.prepare("INSERT INTO mcq_item_editorial_metadata(item_id,item_version,editorial_status,source_version_id,reference_type,reference_locator,reference_label,corpus_id,corpus_version,content_checksum,imported_at) VALUES('fk-item',1,'PUBLISHED','missing-source','PAGE','1','Reference','corpus',1,'checksum','now')").run()).toThrow(); });
});
