import { describe,expect,it,vi } from "vitest";
import type { CalculationsApi } from "@/infrastructure/calculations/server-calculations";
import { createCalculationsHandlers } from "./route";
const id=(n:number)=>`10000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const setup=()=>{const api={exercise:{execute:vi.fn().mockResolvedValue({id:id(1)})},submit:{execute:vi.fn().mockResolvedValue({evaluation:{correct:true}})},retest:{execute:vi.fn().mockResolvedValue({id:id(4)})}} as unknown as CalculationsApi;return{api,handlers:createCalculationsHandlers(async()=>api)}};
describe("/api/calculations",()=>{
  it("loads an exercise and preserves trace_id",async()=>{const {handlers}=setup();const response=await handlers.GET(new Request(`http://x/api/calculations?exerciseVersionId=${id(1)}`,{headers:{"x-trace-id":"trace-calc"}}));expect(response.status).toBe(200);expect(response.headers.get("x-trace-id")).toBe("trace-calc");});
  it("submits a strictly validated finite calculation",async()=>{const {api,handlers}=setup();const response=await handlers.POST(new Request("http://x/api/calculations",{method:"POST",body:JSON.stringify({action:"submit",learnerId:id(2),exerciseVersionId:id(1),steps:[{value:1,unit:"g"}],result:{value:1000,unit:"mg"}})}));expect(response.status).toBe(201);expect(api.submit.execute).toHaveBeenCalledOnce();});
  it("rejects invalid identifiers, unknown units and non-finite payloads before loading runtime",async()=>{const load=vi.fn();const handlers=createCalculationsHandlers(load);for(const body of [{action:"submit",learnerId:"bad",exerciseVersionId:id(1),steps:[{value:1,unit:"kg"}],result:{value:1,unit:"mg"}},{action:"prepareRetest",sourceAttemptId:"bad",exerciseVersionId:id(1)}])expect((await handlers.POST(new Request("http://x",{method:"POST",body:JSON.stringify(body)}))).status).toBe(400);expect(load).not.toHaveBeenCalled();});
  it("prepares a traceable retest",async()=>{const {api,handlers}=setup();const response=await handlers.POST(new Request("http://x",{method:"POST",body:JSON.stringify({action:"prepareRetest",sourceAttemptId:id(3),exerciseVersionId:id(1)})}));expect(response.status).toBe(201);expect(api.retest.execute).toHaveBeenCalledOnce();});
  it("maps internal failures without exposing details",async()=>{const api={exercise:{execute:vi.fn()},submit:{execute:vi.fn().mockRejectedValue(new Error("sqlite secret"))},retest:{execute:vi.fn()}} as unknown as CalculationsApi;const handlers=createCalculationsHandlers(async()=>api);const response=await handlers.POST(new Request("http://x",{method:"POST",body:JSON.stringify({action:"submit",learnerId:id(2),exerciseVersionId:id(1),steps:[{value:1,unit:"g"}],result:{value:1,unit:"g"}})}));expect(response.status).toBe(500);expect(JSON.stringify(await response.json())).not.toContain("sqlite secret");});
});
