import {assertSessionActive,assertUuid,effectiveSessionState,OsceError,publicStation,type OsceAssessment,type OsceDebrief,type OsceInteraction,type OsceRemediationLink,type OsceSession} from "@/domain/osce";
import type {OsceAssessmentPolicy,OsceClock,OsceIds,OsceLogger,OsceRemediationPort,OsceRepository} from "./osce-ports";
type Deps=Readonly<{repository:OsceRepository;ids:OsceIds;clock:OsceClock;logger:OsceLogger;policy:OsceAssessmentPolicy;remediation:OsceRemediationPort}>;
export class OsceService{
 constructor(private readonly d:Deps){}
 async getStation(id:string){assertUuid(id,"stationVersionId");const station=await this.d.repository.findStationVersion(id);if(!station)throw new OsceError("OSCE_VERSION_NOT_FOUND","Station version not found.");return publicStation(station);}
 async start(input:Readonly<{learnerId:string;stationVersionId:string;traceId:string}>){assertUuid(input.learnerId,"learnerId");const station=await this.d.repository.findStationVersion(input.stationVersionId);if(!station||station.status!=="PUBLISHED")throw new OsceError("OSCE_VERSION_NOT_FOUND","Published station version not found.");const startedAt=this.d.clock.now();const session:OsceSession=Object.freeze({id:this.d.ids.next(),learnerId:input.learnerId,stationVersionId:station.id,state:"ACTIVE",startedAt,durationSeconds:station.durationSeconds,expiresAt:new Date(Date.parse(startedAt)+station.durationSeconds*1000).toISOString(),completedAt:null});await this.d.repository.saveSession(session);this.d.logger.event({name:"osce.session_started",traceId:input.traceId,context:{sessionId:session.id,stationVersionId:station.id,state:session.state}});return session;}
 async state(sessionId:string){const session=await this.session(sessionId);const station=await this.station(session.stationVersionId);const revealed=await this.d.repository.listRevealedDisclosures(session.id);const ids=new Set(revealed.map(x=>x.disclosureId));return Object.freeze({session:{...session,state:effectiveSessionState(session,this.d.clock.now())},station:publicStation(station),disclosures:station.disclosures.filter(x=>ids.has(x.id)).map(({id,order,content})=>({id,order,content})),assessment:session.state==="COMPLETED"?await this.d.repository.findAssessment(session.id):null,debrief:session.state==="COMPLETED"?await this.d.repository.findDebrief(session.id):null});}
 async interact(input:Readonly<{sessionId:string;roleId:string;text:string;disclosureId?:string|null;traceId:string}>){const session=await this.session(input.sessionId);assertSessionActive(session,this.d.clock.now());const station=await this.station(session.stationVersionId);if(!station.roles.some(x=>x.id===input.roleId)||!input.text.trim()||input.text.length>4000)throw new OsceError("OSCE_INVALID","Interaction is invalid.");const sequence=(await this.d.repository.listInteractions(session.id)).length+1;const value:OsceInteraction=Object.freeze({id:this.d.ids.next(),sessionId:session.id,roleId:input.roleId,sequence,timestamp:this.d.clock.now(),text:input.text,disclosureId:input.disclosureId??null});await this.d.repository.appendInteraction(value);this.d.logger.event({name:"osce.interaction_recorded",traceId:input.traceId,context:{sessionId:session.id,roleId:input.roleId,order:sequence}});return value;}
 async reveal(input:Readonly<{sessionId:string;disclosureId:string;traceId:string}>){const session=await this.session(input.sessionId);assertSessionActive(session,this.d.clock.now());const station=await this.station(session.stationVersionId);const disclosure=station.disclosures.find(x=>x.id===input.disclosureId);const count=(await this.d.repository.listInteractions(session.id)).length;if(!disclosure||(disclosure.triggerType==="INTERACTION_COUNT"&&count<(disclosure.triggerValue??0)))throw new OsceError("OSCE_DISCLOSURE_FORBIDDEN","Disclosure is not allowed.");const revealedAt=this.d.clock.now();await this.d.repository.revealDisclosure(session.id,disclosure.id,revealedAt);this.d.logger.event({name:"osce.disclosure_revealed",traceId:input.traceId,context:{sessionId:session.id,order:disclosure.order}});return {disclosureId:disclosure.id,revealedAt};}
 async complete(input:Readonly<{sessionId:string;traceId:string}>){const session=await this.session(input.sessionId);assertSessionActive(session,this.d.clock.now());const station=await this.station(session.stationVersionId);const interactions=await this.d.repository.listInteractions(session.id);const completed:OsceSession=Object.freeze({...session,state:"COMPLETED",completedAt:this.d.clock.now()});await this.d.repository.saveSession(completed);const criteria=this.d.policy.assess(station,interactions);const assessment:OsceAssessment=Object.freeze({id:this.d.ids.next(),sessionId:session.id,ruleVersion:this.d.policy.ruleVersion,result:criteria.every(x=>x.passed&&!x.critical)?"SATISFACTORY":"NEEDS_REMEDIATION",createdAt:this.d.clock.now(),criteria:Object.freeze([...criteria])});await this.d.repository.saveAssessment(assessment);const failed=criteria.filter(x=>!x.passed);const debrief:OsceDebrief=Object.freeze({id:this.d.ids.next(),sessionId:session.id,strengths:criteria.filter(x=>x.passed).map(x=>x.criterionId),unmetCriteria:failed.map(x=>x.criterionId),criticalErrors:failed.filter(x=>x.critical).map(x=>x.criterionId),explanations:failed.map(x=>x.justification),objectiveIds:station.objectiveIds,correctiveActions:failed.map(()=>"TARGETED_PRACTICE"),nextPractice:failed.length?"RETEST_VARIANT":"ADVANCE",createdAt:this.d.clock.now()});await this.d.repository.saveDebrief(debrief);for(const criterion of failed){const link:OsceRemediationLink={id:this.d.ids.next(),learnerId:session.learnerId,sessionId:session.id,stationVersionId:station.id,criterionId:criterion.criterionId,errorCategory:"OSCE_PERFORMANCE",critical:criterion.critical,evidenceRef:criterion.evidence,ruleVersion:this.d.policy.ruleVersion,createdAt:this.d.clock.now()};await this.d.repository.saveRemediationLink(link);await this.d.remediation.record(link);}this.d.logger.event({name:"osce.session_completed",traceId:input.traceId,context:{sessionId:session.id,state:"COMPLETED"}});this.d.logger.event({name:"osce.assessment_completed",traceId:input.traceId,context:{sessionId:session.id,critical:failed.some(x=>x.critical),result:assessment.result}});return {session:completed,assessment,debrief};}
 async replay(sessionId:string){const value=await this.d.repository.getReplay(sessionId);if(!value)throw new OsceError("OSCE_SESSION_NOT_FOUND","Replay not found.");if(value.session.state!=="COMPLETED")throw new OsceError("OSCE_PRIVATE_CONTENT","Replay is available after completion.");return value;}
 private async session(id:string){assertUuid(id,"sessionId");const value=await this.d.repository.findSession(id);if(!value)throw new OsceError("OSCE_SESSION_NOT_FOUND","Session not found.");if(effectiveSessionState(value,this.d.clock.now())==="EXPIRED"&&value.state==="ACTIVE"){const expired=Object.freeze({...value,state:"EXPIRED" as const});await this.d.repository.saveSession(expired);return expired;}return value;} private async station(id:string){const value=await this.d.repository.findStationVersion(id);if(!value)throw new OsceError("OSCE_VERSION_NOT_FOUND","Station not found.");return value;}
}
