import "server-only";
import type { ClinicalCase, CoachingSession, LearnerSignal } from "@/domain/coach/clinical-models";
import type { ClinicalCaseRepository, CoachingSessionRepository, LearnerSignalPort } from "@/application/coach/coach-ports";
import type { SqliteExecutor } from "@/infrastructure/database/sqlite/sqlite-executor";

type SessionRow = Readonly<{ session_id:string;mode:CoachingSession["mode"];objective_id:string;learning_objective:string;language:"fr"|"en";status:CoachingSession["status"];current_step:CoachingSession["currentStep"];learner_level:CoachingSession["learnerLevel"];started_at:string;updated_at:string;completed_at:string|null;source_scope_json:string;evidence_refs_json:string;current_case_id:string|null;hint_level:CoachingSession["hintLevel"];attempt_count:number;learner_signals_json:string;learner_answers_json:string;pending_teach_back:number;session_version:number;case_json:string}>;
const parse = (row: SessionRow): CoachingSession => ({ sessionId:row.session_id,mode:row.mode,objectiveId:row.objective_id,learningObjective:row.learning_objective,language:row.language,status:row.status,currentStep:row.current_step,learnerLevel:row.learner_level,startedAt:row.started_at,updatedAt:row.updated_at,completedAt:row.completed_at,sourceScope:JSON.parse(row.source_scope_json) as string[],evidenceRefs:JSON.parse(row.evidence_refs_json) as string[],currentCaseId:row.current_case_id,hintLevel:row.hint_level,attemptCount:row.attempt_count,learnerSignals:JSON.parse(row.learner_signals_json) as LearnerSignal[],learnerAnswers:JSON.parse(row.learner_answers_json) as string[],pendingTeachBack:row.pending_teach_back===1,sessionVersion:row.session_version });

export class SqliteCoachStore {
  private readonly cases = new Map<string,ClinicalCase>();
  constructor(private readonly database:SqliteExecutor) {}
  saveCase(value:ClinicalCase){this.cases.set(value.caseId,value);}
  findCase(id:string):ClinicalCase|null{const cached=this.cases.get(id);if(cached)return cached;const row=this.database.all<{case_json:string}>("SELECT case_json FROM coaching_sessions WHERE current_case_id=? ORDER BY updated_at DESC LIMIT 1",id)[0];return row?JSON.parse(row.case_json) as ClinicalCase:null;}
  saveSession(value:CoachingSession){const clinicalCase=value.currentCaseId?this.cases.get(value.currentCaseId):null;const caseJson=clinicalCase?JSON.stringify(clinicalCase):this.database.all<{case_json:string}>("SELECT case_json FROM coaching_sessions WHERE session_id=?",value.sessionId)[0]?.case_json??"null";this.database.run(`INSERT INTO coaching_sessions(session_id,mode,objective_id,learning_objective,language,status,current_step,learner_level,started_at,updated_at,completed_at,source_scope_json,evidence_refs_json,current_case_id,hint_level,attempt_count,learner_signals_json,learner_answers_json,pending_teach_back,session_version,case_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(session_id) DO UPDATE SET status=excluded.status,current_step=excluded.current_step,updated_at=excluded.updated_at,completed_at=excluded.completed_at,evidence_refs_json=excluded.evidence_refs_json,current_case_id=excluded.current_case_id,hint_level=excluded.hint_level,attempt_count=excluded.attempt_count,learner_signals_json=excluded.learner_signals_json,learner_answers_json=excluded.learner_answers_json,pending_teach_back=excluded.pending_teach_back,session_version=excluded.session_version,case_json=excluded.case_json`,value.sessionId,value.mode,value.objectiveId,value.learningObjective,value.language,value.status,value.currentStep,value.learnerLevel,value.startedAt,value.updatedAt,value.completedAt,JSON.stringify(value.sourceScope),JSON.stringify(value.evidenceRefs),value.currentCaseId,value.hintLevel,value.attemptCount,JSON.stringify(value.learnerSignals),JSON.stringify(value.learnerAnswers),value.pendingTeachBack?1:0,value.sessionVersion,caseJson);}
  findSession(id:string):CoachingSession|null{const row=this.database.all<SessionRow>("SELECT * FROM coaching_sessions WHERE session_id=?",id)[0];if(!row)return null;const clinicalCase=JSON.parse(row.case_json) as ClinicalCase|null;if(clinicalCase)this.cases.set(clinicalCase.caseId,clinicalCase);return parse(row);}
  record(sessionId:string,signal:LearnerSignal){this.database.run("INSERT INTO coach_learner_signals(session_id,objective_id,result,confidence,duration_ms,hint_level,error_type,safety_signal_missed,teachback_result,transfer_result) VALUES(?,?,?,?,?,?,?,?,?,?)",sessionId,signal.objectiveId,signal.result,signal.confidence,signal.durationMs,signal.hintLevel,signal.errorType,signal.safetySignalMissed?1:0,signal.teachBackResult,signal.transferResult);}
}
export class SqliteCoachingSessionRepository implements CoachingSessionRepository{constructor(private readonly store:SqliteCoachStore){}save(value:CoachingSession){this.store.saveSession(value);}find(id:string){return this.store.findSession(id);}}
export class SqliteClinicalCaseRepository implements ClinicalCaseRepository{constructor(private readonly store:SqliteCoachStore){}save(value:ClinicalCase){this.store.saveCase(value);}find(id:string){return this.store.findCase(id);}}
export class SqliteLearnerSignalRepository implements LearnerSignalPort{constructor(private readonly store:SqliteCoachStore){}record(id:string,value:LearnerSignal){this.store.record(id,value);}}
