import type {OsceRepository} from "@/application/osce/osce-ports";
import {defineOsceStationVersion,type OsceAssessment,type OsceDebrief,type OsceInteraction,type OsceRemediationLink,type OsceSession,type OsceStationVersion} from "@/domain/osce";
import type {SqliteExecutor} from "@/infrastructure/database/sqlite/sqlite-executor";
type Row=Record<string,unknown>;
export class SqliteOsceRepository implements OsceRepository{
 constructor(private readonly db:SqliteExecutor){}
 async saveStationVersion(v:OsceStationVersion){this.db.run("INSERT OR IGNORE INTO osce_stations VALUES(?,?,?)",v.stationId,v.code,v.createdAt);this.db.run("INSERT INTO osce_station_versions VALUES(?,?,?,?,?,?,?,?,?,?)",v.id,v.stationId,v.version,v.title,v.durationSeconds,v.scenario,v.status,v.provenance,v.createdAt,v.publishedAt);for(const id of v.objectiveIds)this.db.run("INSERT INTO osce_station_objectives VALUES(?,?)",v.id,id);for(const x of v.roles)this.db.run("INSERT INTO osce_station_roles VALUES(?,?,?,?,?)",x.id,v.id,x.type,x.label,x.order);for(const x of v.disclosures)this.db.run("INSERT INTO osce_disclosures VALUES(?,?,?,?,?,?)",x.id,v.id,x.order,x.triggerType,x.triggerValue,x.content);this.db.run("INSERT INTO osce_rubrics VALUES(?,?,?)",v.rubric.id,v.id,v.rubric.ruleVersion);for(const x of v.rubric.criteria)this.db.run("INSERT INTO osce_rubric_criteria VALUES(?,?,?,?,?,?,?)",x.id,v.rubric.id,x.description,x.competency,x.importance,x.critical?1:0,x.order);}
 async findStationVersion(id:string){const v=this.db.all<Row>("SELECT v.*,s.code FROM osce_station_versions v JOIN osce_stations s ON s.station_id=v.station_id WHERE v.station_version_id=?",id)[0];if(!v)return null;const roles=this.db.all<Row>("SELECT * FROM osce_station_roles WHERE station_version_id=? ORDER BY role_order",id).map(x=>({id:String(x.role_id),type:x.role_type as never,label:String(x.label),order:Number(x.role_order)}));const disclosures=this.db.all<Row>("SELECT * FROM osce_disclosures WHERE station_version_id=? ORDER BY disclosure_order",id).map(x=>({id:String(x.disclosure_id),order:Number(x.disclosure_order),triggerType:x.trigger_type as never,triggerValue:x.trigger_value===null?null:Number(x.trigger_value),content:String(x.content)}));const rubric=this.db.all<Row>("SELECT * FROM osce_rubrics WHERE station_version_id=?",id)[0]!;const criteria=this.db.all<Row>("SELECT * FROM osce_rubric_criteria WHERE rubric_id=? ORDER BY criterion_order",String(rubric.rubric_id)).map(x=>({id:String(x.criterion_id),description:String(x.description),competency:String(x.competency),importance:Number(x.importance),critical:Number(x.critical)===1,order:Number(x.criterion_order)}));return defineOsceStationVersion({id:String(v.station_version_id),stationId:String(v.station_id),version:Number(v.version),code:String(v.code),title:String(v.title),objectiveIds:this.db.all<Row>("SELECT learning_objective_id FROM osce_station_objectives WHERE station_version_id=?",id).map(x=>String(x.learning_objective_id)),durationSeconds:Number(v.duration_seconds),roles,scenario:String(v.scenario),disclosures,rubric:{id:String(rubric.rubric_id),ruleVersion:String(rubric.rule_version),criteria},status:v.status as never,provenance:String(v.provenance),createdAt:String(v.created_at),publishedAt:v.published_at===null?null:String(v.published_at)});}
 async saveSession(v:OsceSession){this.db.run("INSERT INTO osce_sessions VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(session_id) DO UPDATE SET state=excluded.state,completed_at=excluded.completed_at",v.id,v.learnerId,v.stationVersionId,v.state,v.startedAt,v.durationSeconds,v.expiresAt,v.completedAt);}
 async findSession(id:string){const x=this.db.all<Row>("SELECT * FROM osce_sessions WHERE session_id=?",id)[0];return x?{id:String(x.session_id),learnerId:String(x.learner_id),stationVersionId:String(x.station_version_id),state:x.state as never,startedAt:String(x.started_at),durationSeconds:Number(x.duration_seconds),expiresAt:String(x.expires_at),completedAt:x.completed_at===null?null:String(x.completed_at)}:null;}
 async appendInteraction(v:OsceInteraction){this.db.run("INSERT INTO osce_interactions VALUES(?,?,?,?,?,?,?)",v.id,v.sessionId,v.roleId,v.sequence,v.timestamp,v.text,v.disclosureId);}
 async listInteractions(id:string){return this.db.all<Row>("SELECT * FROM osce_interactions WHERE session_id=? ORDER BY sequence",id).map(x=>({id:String(x.interaction_id),sessionId:String(x.session_id),roleId:String(x.role_id),sequence:Number(x.sequence),timestamp:String(x.timestamp),text:String(x.text),disclosureId:x.disclosure_id===null?null:String(x.disclosure_id)}));}
 async revealDisclosure(s:string,d:string,t:string){this.db.run("INSERT OR IGNORE INTO osce_session_disclosures VALUES(?,?,?)",s,d,t);}
 async listRevealedDisclosures(id:string){return this.db.all<Row>("SELECT disclosure_id,revealed_at FROM osce_session_disclosures WHERE session_id=? ORDER BY revealed_at",id).map(x=>({disclosureId:String(x.disclosure_id),revealedAt:String(x.revealed_at)}));}
 async saveAssessment(v:OsceAssessment){this.db.run("INSERT INTO osce_assessments VALUES(?,?,?,?,?)",v.id,v.sessionId,v.ruleVersion,v.result,v.createdAt);for(const x of v.criteria)this.db.run("INSERT INTO osce_assessment_criteria VALUES(?,?,?,?,?,?)",v.id,x.criterionId,x.passed?1:0,x.justification,x.evidence,x.critical?1:0);}
 async findAssessment(id:string){const a=this.db.all<Row>("SELECT * FROM osce_assessments WHERE session_id=?",id)[0];if(!a)return null;return{id:String(a.assessment_id),sessionId:id,ruleVersion:String(a.rule_version),result:a.result as never,createdAt:String(a.created_at),criteria:this.db.all<Row>("SELECT * FROM osce_assessment_criteria WHERE assessment_id=?",String(a.assessment_id)).map(x=>({criterionId:String(x.criterion_id),passed:Number(x.passed)===1,justification:String(x.justification),evidence:String(x.evidence),critical:Number(x.critical)===1}))};}
 async saveDebrief(v:OsceDebrief){this.db.run("INSERT INTO osce_debriefs VALUES(?,?,?,?)",v.id,v.sessionId,JSON.stringify(v),v.createdAt);} async findDebrief(id:string){const x=this.db.all<Row>("SELECT payload_json FROM osce_debriefs WHERE session_id=?",id)[0];return x?JSON.parse(String(x.payload_json)) as OsceDebrief:null;}
 async saveRemediationLink(v:OsceRemediationLink){this.db.run("INSERT INTO osce_remediation_links VALUES(?,?,?,?,?,?,?,?,?,?)",v.id,v.learnerId,v.sessionId,v.stationVersionId,v.criterionId,v.errorCategory,v.critical?1:0,v.evidenceRef,v.ruleVersion,v.createdAt);} async listRemediationLinks(id:string){return this.db.all<Row>("SELECT * FROM osce_remediation_links WHERE session_id=?",id).map(x=>({id:String(x.remediation_link_id),learnerId:String(x.learner_id),sessionId:String(x.session_id),stationVersionId:String(x.station_version_id),criterionId:String(x.criterion_id),errorCategory:String(x.error_category),critical:Number(x.critical)===1,evidenceRef:String(x.evidence_ref),ruleVersion:String(x.rule_version),createdAt:String(x.created_at)}));}
 async getReplay(id:string){const session=await this.findSession(id);if(!session)return null;const station=await this.findStationVersion(session.stationVersionId);if(!station)return null;return{session,stationVersionId:station.id,rubricVersion:station.rubric.ruleVersion,interactions:await this.listInteractions(id),disclosures:await this.listRevealedDisclosures(id),assessment:await this.findAssessment(id),debrief:await this.findDebrief(id),remediationLinks:await this.listRemediationLinks(id)};}
}
