export type MigrationErrorCode =
  | "INVALID_MIGRATION_DEFINITION"
  | "DUPLICATE_MIGRATION_ID"
  | "DUPLICATE_MIGRATION_VERSION"
  | "INVALID_MIGRATION_CHAIN"
  | "MIGRATION_HISTORY_PERSISTENCE_ERROR"
  | "INVALID_MIGRATION_HISTORY"
  | "UNKNOWN_APPLIED_MIGRATION"
  | "MIGRATION_CHECKSUM_MISMATCH"
  | "MIGRATION_HISTORY_AHEAD"
  | "SCHEMA_INSPECTION_ERROR"
  | "DATABASE_NOT_FRESH"
  | "FRESH_BOOTSTRAP_VALIDATION_ERROR"
  | "MIGRATION_EXECUTION_ERROR"
  | "UNKNOWN_LEGACY_SCHEMA"
  | "PARTIAL_LEGACY_SCHEMA"
  | "AMBIGUOUS_LEGACY_SCHEMA"
  | "LEGACY_ADOPTION_NOT_ALLOWED"
  | "LEGACY_ADOPTION_FAILED"
  | "LEGACY_SCHEMA_CHANGED_DURING_ADOPTION"
  | "IMPORT_JOURNAL_SCHEMA_INCOMPATIBLE"
  | "IMPORT_JOURNAL_SCHEMA_MISSING"
  | "MIGRATION_SCHEMA_POSTCONDITION_FAILED";

export class MigrationError extends Error {
  constructor(
    readonly code: MigrationErrorCode,
    message: string,
    options?: ErrorOptions,
  ) {
    super(message, options);
    this.name = "MigrationError";
  }
}
