import type { CalculationsRepository } from "@/application/calculations/calculations-ports";
import { defineCalculationExerciseVersion, type CalculationAttempt, type CalculationExerciseVersion, type CalculationRetest } from "@/domain/calculations";
import type { SqliteExecutor } from "@/infrastructure/database/sqlite/sqlite-executor";
type VersionRow={exercise_version_id:string;exercise_id:string;learning_objective_id:string;version:number;difficulty:CalculationExerciseVersion["difficulty"];inputs_json:string;steps_json:string;expected_value:number;result_unit:CalculationExerciseVersion["expectedResult"]["unit"];dimension:CalculationExerciseVersion["dimension"];tolerance:number;plausibility_min:number;plausibility_max:number;status:CalculationExerciseVersion["status"];created_at:string};
type AttemptRow={attempt_id:string;learner_id:string;exercise_version_id:string;submitted_at:string;submission_json:string;evaluation_json:string};
type RetestRow={retest_id:string;source_attempt_id:string;exercise_version_id:string;created_at:string;result_attempt_id:string|null;resolved:number};
export class SqliteCalculationsRepository implements CalculationsRepository {
  constructor(private readonly database:SqliteExecutor){}
  async saveExerciseVersion(value:CalculationExerciseVersion){this.database.run("INSERT OR IGNORE INTO calculation_exercises(exercise_id,learning_objective_id,created_at) VALUES(?,?,?)",value.exerciseId,value.learningObjectiveId,value.createdAt);this.database.run("INSERT INTO calculation_exercise_versions(exercise_version_id,exercise_id,version,difficulty,inputs_json,steps_json,expected_value,result_unit,dimension,tolerance,plausibility_min,plausibility_max,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",value.id,value.exerciseId,value.version,value.difficulty,JSON.stringify(value.inputs),JSON.stringify(value.steps),value.expectedResult.value,value.expectedResult.unit,value.dimension,value.tolerance,value.plausibility.min,value.plausibility.max,value.status,value.createdAt);}
  async findExerciseVersion(id:string){const row=this.database.all<VersionRow>("SELECT v.*,e.learning_objective_id FROM calculation_exercise_versions v JOIN calculation_exercises e ON e.exercise_id=v.exercise_id WHERE v.exercise_version_id=?",id)[0];return row?defineCalculationExerciseVersion({id:row.exercise_version_id,exerciseId:row.exercise_id,learningObjectiveId:row.learning_objective_id,version:row.version,difficulty:row.difficulty,inputs:JSON.parse(row.inputs_json),steps:JSON.parse(row.steps_json),expectedResult:{value:row.expected_value,unit:row.result_unit},dimension:row.dimension,tolerance:row.tolerance,plausibility:{min:row.plausibility_min,max:row.plausibility_max},status:row.status,createdAt:row.created_at}):null;}
  async saveAttempt(value:CalculationAttempt){this.database.run("INSERT INTO calculation_attempts(attempt_id,learner_id,exercise_version_id,submitted_at,submission_json,evaluation_json,mastered) VALUES(?,?,?,?,?,?,?)",value.id,value.learnerId,value.exerciseVersionId,value.submittedAt,JSON.stringify(value.submission),JSON.stringify(value.evaluation),value.evaluation.mastered?1:0);value.evaluation.observations.forEach((item,index)=>this.database.run("INSERT INTO calculation_observations(observation_id,attempt_id,step_position,parent_category,error_category,critical,message) VALUES(?,?,?,?,?,?,?)",`${value.id}:${index}`,value.id,item.step,item.parentCategory,item.category,item.critical?1:0,item.message));}
  private attempt(row:AttemptRow):CalculationAttempt{return Object.freeze({id:row.attempt_id,learnerId:row.learner_id,exerciseVersionId:row.exercise_version_id,submittedAt:row.submitted_at,submission:Object.freeze(JSON.parse(row.submission_json)),evaluation:Object.freeze(JSON.parse(row.evaluation_json))});}
  async findAttempt(id:string){const row=this.database.all<AttemptRow>("SELECT * FROM calculation_attempts WHERE attempt_id=?",id)[0];return row?this.attempt(row):null;}
  async listAttempts(exerciseVersionId:string,learnerId:string){return Object.freeze(this.database.all<AttemptRow>("SELECT * FROM calculation_attempts WHERE exercise_version_id=? AND learner_id=? ORDER BY submitted_at,attempt_id",exerciseVersionId,learnerId).map(row=>this.attempt(row)));}
  async saveRetest(value:CalculationRetest){this.database.run("INSERT INTO calculation_retests(retest_id,source_attempt_id,exercise_version_id,created_at,result_attempt_id,resolved) VALUES(?,?,?,?,?,?)",value.id,value.sourceAttemptId,value.exerciseVersionId,value.createdAt,value.resultAttemptId,value.resolved?1:0);}
  async findRetest(id:string){const row=this.database.all<RetestRow>("SELECT * FROM calculation_retests WHERE retest_id=?",id)[0];return row?Object.freeze({id:row.retest_id,sourceAttemptId:row.source_attempt_id,exerciseVersionId:row.exercise_version_id,createdAt:row.created_at,resultAttemptId:row.result_attempt_id,resolved:row.resolved===1}):null;}
}
