"use client";

import { useState } from "react";
import { BookOpen, Send, Sparkles } from "lucide-react";
import { useAppState } from "@/hooks/use-state";
import { Loading, Notice, PageHeader } from "@/components/ui";

type Citation={document:string;excerpt:string};
export default function AiPage(){const {data,refresh}=useAppState();const [question,setQuestion]=useState("");const [mode,setMode]=useState("Explication");const [busy,setBusy]=useState(false);const [result,setResult]=useState<{answer:string;citations:Citation[];support:string}|null>(null);if(!data)return <Loading/>;
async function ask(e:React.FormEvent){e.preventDefault();setBusy(true);try{const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,mode})});setResult(await response.json());setQuestion("");await refresh()}finally{setBusy(false)}}
return <div className="mx-auto max-w-6xl"><PageHeader eyebrow="FEAT-016 · Citations obligatoires" title="Professeur IA" description="Posez une question à votre bibliothèque. Les passages documentaires sont distingués des explications générées."/><div className="grid gap-6 xl:grid-cols-[1fr_310px]"><section><div className="card mb-5 p-5"><form onSubmit={ask}><div className="mb-3 flex flex-wrap gap-2">{["Explication","Simplification","Comparaison","Analogie","Mode socratique","Résumé"].map(item=><button type="button" key={item} onClick={()=>setMode(item)} className={`btn py-2 text-xs ${mode===item?"btn-primary":"btn-secondary"}`}>{item}</button>)}</div><textarea className="field min-h-28 resize-y" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Que souhaitez-vous comprendre?" minLength={3} required/><div className="mt-3 flex items-center justify-between"><span className="text-xs text-[var(--muted-foreground)]">Mode local · aucun appel payant</span><button disabled={busy} className="btn btn-primary"><Send size={16}/>{busy?"Recherche...":"Envoyer"}</button></div></form></div>{result&&<article className="card p-6"><div className="mb-4 flex items-center gap-2"><Sparkles className="text-[var(--primary)]"/><h2 className="m-0">Réponse</h2><span className="badge ml-auto">Appui {result.support.toLowerCase()}</span></div><p className="whitespace-pre-line leading-7">{result.answer}</p>{result.citations.length>0&&<div className="mt-6 border-t border-[var(--border)] pt-5"><h3 className="flex items-center gap-2"><BookOpen size={18}/>Sources utilisées</h3>{result.citations.map((citation,index)=><div key={index} className="mb-3 rounded-xl bg-[var(--accent)] p-4"><div className="mb-1 text-sm font-black">[{index+1}] {citation.document}</div><div className="text-sm text-[var(--muted-foreground)]">{citation.excerpt}</div></div>)}</div>}</article>}</section><aside className="space-y-4"><Notice>Le contenu des documents est traité comme une donnée non fiable, jamais comme une instruction. Vérifiez toute décision clinique importante.</Notice><div className="card p-5"><h3 className="mt-0">Conversations récentes</h3>{data.messages.slice(-6).map(msg=><div key={msg.id} className="border-t border-[var(--border)] py-3 text-sm"><strong>{msg.role==="user"?"Vous":"Mentor"}</strong><p className="mb-0 mt-1 line-clamp-3 text-[var(--muted-foreground)]">{msg.content}</p></div>)}</div></aside></div></div>}
