import type { ClinicalCase, CoachingSession, LearnerSignal } from "@/domain/coach/clinical-models";
import { validateClinicalCase } from "@/domain/coach/clinical-case-validator";
import { ClinicalSafetyEngine } from "@/domain/coach/clinical-safety-engine";
import { MedicationReviewEngine } from "@/domain/coach/medication-review-engine";
import { AnswerEvaluator } from "./answer-evaluator";
import type { ClinicalCaseRepository, ClinicalEvidenceService, CoachIdentityPort, CoachLoggerPort, CoachProvider, CoachingSessionRepository, LearnerSignalPort } from "./coach-ports";
import { TransferCaseGenerator } from "./transfer-case-generator";

export class CoachApplicationError extends Error { constructor(readonly code: "COACH_SESSION_STATE_INVALID" | "COACH_EVIDENCE_INSUFFICIENT" | "COACH_EVIDENCE_CONFLICT" | "COACH_REQUIRED_DATA_MISSING", message: string) { super(message); } }
export class ClinicalCoachOrchestrator {
  constructor(private readonly sessions: CoachingSessionRepository, private readonly cases: ClinicalCaseRepository, private readonly evidence: ClinicalEvidenceService, private readonly signals: LearnerSignalPort, private readonly identity: CoachIdentityPort, private readonly provider: CoachProvider, private readonly logger: CoachLoggerPort, private readonly medicationReview = new MedicationReviewEngine(), private readonly safety = new ClinicalSafetyEngine(), private readonly evaluator = new AnswerEvaluator(), private readonly transfer = new TransferCaseGenerator(identity)) {}
  start(input: Readonly<{ mode: CoachingSession["mode"]; objectiveId: string; learningObjective: string; language: "fr" | "en"; learnerLevel: CoachingSession["learnerLevel"]; clinicalCase: ClinicalCase; sourceScope: readonly string[]; traceId: string }>) {
    const clinicalCase = validateClinicalCase(input.clinicalCase); const now = this.identity.now(); const sessionId = this.identity.id(); this.cases.save(clinicalCase);
    const evidence = this.evidence.loadRules(clinicalCase.evidenceRequirements); const review = this.medicationReview.review(clinicalCase, evidence.rules); const safetySignals = this.safety.prioritize(review);
    const session: CoachingSession = { sessionId, mode: input.mode, objectiveId: input.objectiveId, learningObjective: input.learningObjective, language: input.language, status: "ACTIVE", currentStep: "CASE", learnerLevel: input.learnerLevel, startedAt: now, updatedAt: now, completedAt: null, sourceScope: input.sourceScope, evidenceRefs: evidence.evidenceRefs, currentCaseId: clinicalCase.caseId, hintLevel: 0, attemptCount: 0, learnerSignals: [], learnerAnswers: [], pendingTeachBack: false, sessionVersion: 1 }; this.sessions.save(session);
    this.logger.event({ name: "coach.session.started", traceId: input.traceId, sessionId, status: "success", context: { mode: input.mode } }); this.logger.event({ name: "coach.case.loaded", traceId: input.traceId, sessionId, status: "success" }); this.logger.event({ name: "coach.medication_review.completed", traceId: input.traceId, sessionId, status: "success", context: { medicationCount: clinicalCase.medications.length } }); this.logger.event({ name: "coach.safety_review.completed", traceId: input.traceId, sessionId, status: "success", context: this.metrics(safetySignals, evidence.evidenceRefs.length) });
    return { session, clinicalCase, review, step: this.provider.generateStep({ mode: session.mode, step: session.currentStep, objective: session.learningObjective, hintLevel: 0, safetySignals, evidenceRefs: evidence.evidenceRefs, evidenceStatus: evidence.status }), evidenceStatus: evidence.status, conflicts: evidence.conflicts };
  }
  answer(input: Readonly<{ sessionId: string; answer: string; confidence?: number; durationMs: number; traceId: string }>) {
    if (input.answer.length > 4_000) throw new CoachApplicationError("COACH_SESSION_STATE_INVALID", "Réponse trop volumineuse."); const session = this.sessions.find(input.sessionId); if (!session || session.status !== "ACTIVE" || !session.currentCaseId) throw new CoachApplicationError("COACH_SESSION_STATE_INVALID", "Session Coach invalide."); const clinicalCase = this.cases.find(session.currentCaseId); if (!clinicalCase) throw new CoachApplicationError("COACH_SESSION_STATE_INVALID", "Cas de session introuvable."); const evidence = this.evidence.loadRules(clinicalCase.evidenceRequirements); const review = this.medicationReview.review(clinicalCase, evidence.rules); const safetySignals = this.safety.prioritize(review); const result = session.currentStep === "TEACH_BACK" ? this.evaluator.evaluateTeachBack(input.answer, clinicalCase.expectedFindings) : this.evaluator.evaluate(input.answer, clinicalCase.expectedFindings, safetySignals);
    const errorType = "errorType" in result ? result.errorType : null; const missedSafety = "missedSafety" in result ? result.missedSafety : false; const learnerSignal: LearnerSignal = { objectiveId: session.objectiveId, result: result.result === "NEEDS_REINFORCEMENT" ? "FAIL" : result.result, confidence: input.confidence ?? null, durationMs: input.durationMs, hintLevel: session.hintLevel, errorType, safetySignalMissed: missedSafety, teachBackResult: session.currentStep === "TEACH_BACK" ? result.result as "PASS" | "NEEDS_REINFORCEMENT" : null, transferResult: session.currentStep === "TRANSFER_CASE" ? result.result === "PASS" ? "PASS" : "FAIL" : null };
    const nextStep = result.result === "PASS" ? session.currentStep === "TEACH_BACK" ? "TRANSFER_CASE" : session.currentStep === "TRANSFER_CASE" ? "COMPLETED" : "TEACH_BACK" : session.mode === "SOCRATIC" && session.hintLevel < 4 ? session.currentStep : "CORRECT"; const nextHint = result.result !== "PASS" && session.mode === "SOCRATIC" ? Math.min(4, session.hintLevel + 1) as 0|1|2|3|4 : session.hintLevel; const updated: CoachingSession = { ...session, status: nextStep === "COMPLETED" ? "COMPLETED" : "ACTIVE", currentStep: nextStep, hintLevel: nextHint, attemptCount: session.attemptCount + 1, learnerSignals: [...session.learnerSignals, learnerSignal], learnerAnswers: [...session.learnerAnswers, input.answer], pendingTeachBack: nextStep === "TEACH_BACK", updatedAt: this.identity.now(), completedAt: nextStep === "COMPLETED" ? this.identity.now() : null, sessionVersion: session.sessionVersion + 1 }; this.sessions.save(updated); this.signals.record(session.sessionId, learnerSignal);
    this.logger.event({ name: "coach.answer.evaluated", traceId: input.traceId, sessionId: session.sessionId, status: result.result === "PASS" ? "success" : "degraded", context: { result: result.result, hintLevel: nextHint } }); if (errorType) this.logger.event({ name: "coach.error.classified", traceId: input.traceId, sessionId: session.sessionId, status: "degraded", context: { errorType } }); if (nextStep === "COMPLETED") this.logger.event({ name: "coach.session.completed", traceId: input.traceId, sessionId: session.sessionId, status: "success" });
    const transferCase = nextStep === "TRANSFER_CASE" ? this.transfer.generate(clinicalCase) : null; if (transferCase) this.cases.save(transferCase); return { session: updated, evaluation: result, transferCase, step: this.provider.generateStep({ mode: updated.mode, step: updated.currentStep, objective: updated.learningObjective, hintLevel: updated.hintLevel, safetySignals, evidenceRefs: evidence.evidenceRefs, evidenceStatus: evidence.status }), evidenceStatus: evidence.status, conflicts: evidence.conflicts };
  }
  resume(sessionId: string) { const session = this.sessions.find(sessionId); if (!session) throw new CoachApplicationError("COACH_SESSION_STATE_INVALID", "Session Coach introuvable."); return session; }
  private metrics(signals: readonly { signalType: string }[], evidenceCount: number) { const count = (type: string) => signals.filter(({ signalType }) => signalType === type).length; return { interactionSignalCount: count("INTERACTION_SIGNAL"), allergySignalCount: count("ALLERGY_SIGNAL"), doseSignalCount: count("DOSE_SIGNAL"), contraindicationSignalCount: count("CONTRAINDICATION_SIGNAL"), duplicationSignalCount: count("DUPLICATION_SIGNAL"), monitoringSignalCount: count("MONITORING_SIGNAL"), missingDataCount: count("MISSING_DATA_SIGNAL"), evidenceCount }; }
}
