import type { SqliteExecutor } from "../../sqlite-executor";
import { MigrationError } from "../migration-errors";
import { SqliteSchemaInspector } from "../sqlite-schema-inspector";
export const CALCULATIONS_LAB_TABLE_NAMES = ["calculation_exercises","calculation_exercise_versions","calculation_attempts","calculation_observations","calculation_retests"] as const;
export const CALCULATIONS_LAB_STATEMENTS = [
  `CREATE TABLE calculation_exercises (exercise_id TEXT PRIMARY KEY, learning_objective_id TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(learning_objective_id) REFERENCES learning_objectives(learning_objective_id) ON DELETE RESTRICT)`,
  `CREATE TABLE calculation_exercise_versions (exercise_version_id TEXT PRIMARY KEY, exercise_id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>=1), difficulty TEXT NOT NULL CHECK(difficulty IN ('FOUNDATIONAL','INTERMEDIATE','ADVANCED')), inputs_json TEXT NOT NULL, steps_json TEXT NOT NULL, expected_value REAL NOT NULL, result_unit TEXT NOT NULL CHECK(result_unit IN ('mg','g','mL','L')), dimension TEXT NOT NULL CHECK(dimension IN ('MASS','VOLUME')), tolerance REAL NOT NULL CHECK(tolerance>=0), plausibility_min REAL NOT NULL, plausibility_max REAL NOT NULL, status TEXT NOT NULL CHECK(status IN ('DRAFT','ACTIVE','RETIRED')), created_at TEXT NOT NULL, UNIQUE(exercise_id,version), CHECK(plausibility_min<=plausibility_max), FOREIGN KEY(exercise_id) REFERENCES calculation_exercises(exercise_id) ON DELETE RESTRICT)`,
  "CREATE INDEX calculation_exercise_versions_lookup ON calculation_exercise_versions(exercise_id,status,version)",
  `CREATE TABLE calculation_attempts (attempt_id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, exercise_version_id TEXT NOT NULL, submitted_at TEXT NOT NULL, submission_json TEXT NOT NULL, evaluation_json TEXT NOT NULL, mastered INTEGER NOT NULL CHECK(mastered IN (0,1)), FOREIGN KEY(exercise_version_id) REFERENCES calculation_exercise_versions(exercise_version_id) ON DELETE RESTRICT)`,
  "CREATE INDEX calculation_attempts_history ON calculation_attempts(learner_id,exercise_version_id,submitted_at)",
  `CREATE TABLE calculation_observations (observation_id TEXT PRIMARY KEY, attempt_id TEXT NOT NULL, step_position INTEGER, parent_category TEXT NOT NULL CHECK(parent_category='ERR-CALC'), error_category TEXT NOT NULL CHECK(error_category IN ('FORMULA','DATA','CONVERSION','UNIT','DIMENSION','ARITHMETIC','ROUNDING','PLAUSIBILITY')), critical INTEGER NOT NULL CHECK(critical IN (0,1)), message TEXT NOT NULL, FOREIGN KEY(attempt_id) REFERENCES calculation_attempts(attempt_id) ON DELETE RESTRICT)`,
  "CREATE INDEX calculation_observations_attempt ON calculation_observations(attempt_id,critical,error_category)",
  `CREATE TABLE calculation_retests (retest_id TEXT PRIMARY KEY, source_attempt_id TEXT NOT NULL, exercise_version_id TEXT NOT NULL, created_at TEXT NOT NULL, result_attempt_id TEXT, resolved INTEGER NOT NULL CHECK(resolved IN (0,1)), CHECK((resolved=0 AND result_attempt_id IS NULL) OR (resolved=1 AND result_attempt_id IS NOT NULL)), FOREIGN KEY(source_attempt_id) REFERENCES calculation_attempts(attempt_id) ON DELETE RESTRICT, FOREIGN KEY(exercise_version_id) REFERENCES calculation_exercise_versions(exercise_version_id) ON DELETE RESTRICT, FOREIGN KEY(result_attempt_id) REFERENCES calculation_attempts(attempt_id) ON DELETE RESTRICT)`,
  "CREATE INDEX calculation_retests_source ON calculation_retests(source_attempt_id,created_at)",
] as const;
export function assertCalculationsLabSchema(database: SqliteExecutor): void { const tables=new Map(new SqliteSchemaInspector(database).inspect().tables.map(t=>[t.name,t])); if(CALCULATIONS_LAB_TABLE_NAMES.some(name=>!tables.has(name)) || tables.get("calculation_exercise_versions")?.foreignKeys.length!==1 || tables.get("calculation_attempts")?.foreignKeys.length!==1 || tables.get("calculation_retests")?.foreignKeys.length!==3) throw new MigrationError("MIGRATION_SCHEMA_POSTCONDITION_FAILED","Calculations Lab schema is incomplete."); }
export const calculationsLabCoreMigration={id:"MIG-0010",fromVersion:9,toVersion:10,description:"Create Calculations Lab Core schema",checksumMaterial:[...CALCULATIONS_LAB_STATEMENTS,"postcondition:calculations-lab-core-v1"],up:(database:SqliteExecutor)=>{for(const statement of CALCULATIONS_LAB_STATEMENTS) database.run(statement);},validate:assertCalculationsLabSchema} as const;
