import type {SqliteExecutor} from "../../sqlite-executor";
import {MigrationError} from "../migration-errors";
import {SqliteSchemaInspector} from "../sqlite-schema-inspector";
export const OSCE_TABLE_NAMES=["osce_stations","osce_station_versions","osce_station_objectives","osce_station_roles","osce_disclosures","osce_rubrics","osce_rubric_criteria","osce_sessions","osce_interactions","osce_session_disclosures","osce_assessments","osce_assessment_criteria","osce_debriefs","osce_remediation_links"] as const;
export const OSCE_STATEMENTS=[
`CREATE TABLE osce_stations (station_id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL)`,
`CREATE TABLE osce_station_versions (station_version_id TEXT PRIMARY KEY, station_id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>=1), title TEXT NOT NULL, duration_seconds INTEGER NOT NULL CHECK(duration_seconds>0), scenario TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('DRAFT','PUBLISHED','RETIRED')), provenance TEXT NOT NULL, created_at TEXT NOT NULL, published_at TEXT, UNIQUE(station_id,version), FOREIGN KEY(station_id) REFERENCES osce_stations(station_id) ON DELETE RESTRICT)`,
`CREATE INDEX osce_station_versions_lookup ON osce_station_versions(station_id,status,version)`,
`CREATE TABLE osce_station_objectives (station_version_id TEXT NOT NULL, learning_objective_id TEXT NOT NULL, PRIMARY KEY(station_version_id,learning_objective_id), FOREIGN KEY(station_version_id) REFERENCES osce_station_versions(station_version_id) ON DELETE RESTRICT, FOREIGN KEY(learning_objective_id) REFERENCES learning_objectives(learning_objective_id) ON DELETE RESTRICT)`,
`CREATE TABLE osce_station_roles (role_id TEXT PRIMARY KEY, station_version_id TEXT NOT NULL, role_type TEXT NOT NULL CHECK(role_type IN ('LEARNER','PATIENT','CAREGIVER','CLINICIAN','EVALUATOR_SYSTEM')), label TEXT NOT NULL, role_order INTEGER NOT NULL CHECK(role_order>0), UNIQUE(station_version_id,role_order), UNIQUE(station_version_id,role_type), FOREIGN KEY(station_version_id) REFERENCES osce_station_versions(station_version_id) ON DELETE RESTRICT)`,
`CREATE TABLE osce_disclosures (disclosure_id TEXT PRIMARY KEY, station_version_id TEXT NOT NULL, disclosure_order INTEGER NOT NULL CHECK(disclosure_order>0), trigger_type TEXT NOT NULL CHECK(trigger_type IN ('MANUAL','INTERACTION_COUNT')), trigger_value INTEGER, content TEXT NOT NULL, UNIQUE(station_version_id,disclosure_order), FOREIGN KEY(station_version_id) REFERENCES osce_station_versions(station_version_id) ON DELETE RESTRICT)`,
`CREATE TABLE osce_rubrics (rubric_id TEXT PRIMARY KEY, station_version_id TEXT NOT NULL UNIQUE, rule_version TEXT NOT NULL, FOREIGN KEY(station_version_id) REFERENCES osce_station_versions(station_version_id) ON DELETE RESTRICT)`,
`CREATE TABLE osce_rubric_criteria (criterion_id TEXT PRIMARY KEY, rubric_id TEXT NOT NULL, description TEXT NOT NULL, competency TEXT NOT NULL, importance REAL NOT NULL CHECK(importance>0), critical INTEGER NOT NULL CHECK(critical IN (0,1)), criterion_order INTEGER NOT NULL CHECK(criterion_order>0), UNIQUE(rubric_id,criterion_order), FOREIGN KEY(rubric_id) REFERENCES osce_rubrics(rubric_id) ON DELETE RESTRICT)`,
`CREATE TABLE osce_sessions (session_id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, station_version_id TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('ACTIVE','COMPLETED','EXPIRED')), started_at TEXT NOT NULL, duration_seconds INTEGER NOT NULL CHECK(duration_seconds>0), expires_at TEXT NOT NULL, completed_at TEXT, CHECK((state='COMPLETED' AND completed_at IS NOT NULL) OR (state<>'COMPLETED' AND completed_at IS NULL)), FOREIGN KEY(station_version_id) REFERENCES osce_station_versions(station_version_id) ON DELETE RESTRICT)`,
`CREATE INDEX osce_sessions_learner_state ON osce_sessions(learner_id,state,started_at)`,
`CREATE TABLE osce_interactions (interaction_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, role_id TEXT NOT NULL, sequence INTEGER NOT NULL CHECK(sequence>0), timestamp TEXT NOT NULL, text TEXT NOT NULL, disclosure_id TEXT, UNIQUE(session_id,sequence), FOREIGN KEY(session_id) REFERENCES osce_sessions(session_id) ON DELETE RESTRICT, FOREIGN KEY(role_id) REFERENCES osce_station_roles(role_id) ON DELETE RESTRICT, FOREIGN KEY(disclosure_id) REFERENCES osce_disclosures(disclosure_id) ON DELETE RESTRICT)`,
`CREATE INDEX osce_interactions_order ON osce_interactions(session_id,sequence)`,
`CREATE TABLE osce_session_disclosures (session_id TEXT NOT NULL, disclosure_id TEXT NOT NULL, revealed_at TEXT NOT NULL, PRIMARY KEY(session_id,disclosure_id), FOREIGN KEY(session_id) REFERENCES osce_sessions(session_id) ON DELETE RESTRICT, FOREIGN KEY(disclosure_id) REFERENCES osce_disclosures(disclosure_id) ON DELETE RESTRICT)`,
`CREATE INDEX osce_disclosures_revealed ON osce_session_disclosures(session_id,revealed_at)`,
`CREATE TABLE osce_assessments (assessment_id TEXT PRIMARY KEY, session_id TEXT NOT NULL UNIQUE, rule_version TEXT NOT NULL, result TEXT NOT NULL CHECK(result IN ('SATISFACTORY','NEEDS_REMEDIATION')), created_at TEXT NOT NULL, FOREIGN KEY(session_id) REFERENCES osce_sessions(session_id) ON DELETE RESTRICT)`,
`CREATE TABLE osce_assessment_criteria (assessment_id TEXT NOT NULL, criterion_id TEXT NOT NULL, passed INTEGER NOT NULL CHECK(passed IN (0,1)), justification TEXT NOT NULL, evidence TEXT NOT NULL, critical INTEGER NOT NULL CHECK(critical IN (0,1)), PRIMARY KEY(assessment_id,criterion_id), FOREIGN KEY(assessment_id) REFERENCES osce_assessments(assessment_id) ON DELETE RESTRICT, FOREIGN KEY(criterion_id) REFERENCES osce_rubric_criteria(criterion_id) ON DELETE RESTRICT)`,
`CREATE INDEX osce_assessment_lookup ON osce_assessments(session_id,created_at)`,
`CREATE TABLE osce_debriefs (debrief_id TEXT PRIMARY KEY, session_id TEXT NOT NULL UNIQUE, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(session_id) REFERENCES osce_sessions(session_id) ON DELETE RESTRICT)`,
`CREATE TABLE osce_remediation_links (remediation_link_id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, session_id TEXT NOT NULL, station_version_id TEXT NOT NULL, criterion_id TEXT NOT NULL, error_category TEXT NOT NULL, critical INTEGER NOT NULL CHECK(critical IN (0,1)), evidence_ref TEXT NOT NULL, rule_version TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(session_id) REFERENCES osce_sessions(session_id) ON DELETE RESTRICT, FOREIGN KEY(station_version_id) REFERENCES osce_station_versions(station_version_id) ON DELETE RESTRICT, FOREIGN KEY(criterion_id) REFERENCES osce_rubric_criteria(criterion_id) ON DELETE RESTRICT)`,
] as const;
export function assertOsceSchema(db:SqliteExecutor){const tables=new Map(new SqliteSchemaInspector(db).inspect().tables.map(x=>[x.name,x]));if(OSCE_TABLE_NAMES.some(x=>!tables.has(x))||tables.get("osce_sessions")?.foreignKeys.length!==1||tables.get("osce_interactions")?.foreignKeys.length!==3)throw new MigrationError("MIGRATION_SCHEMA_POSTCONDITION_FAILED","OSCE schema is incomplete.");}
export const osceTextCoreMigration={id:"MIG-0011",fromVersion:10,toVersion:11,description:"Create OSCE Text Core schema",checksumMaterial:[...OSCE_STATEMENTS,"postcondition:osce-text-core-v1"],up:(db:SqliteExecutor)=>{for(const statement of OSCE_STATEMENTS)db.run(statement);},validate:assertOsceSchema} as const;
