export type CoachMode = "PROFESSOR" | "CLINICAL_PHARMACIST" | "SOCRATIC" | "TEACH_BACK" | "RAPID_REVIEW";
export type CoachingStep = "CASE" | "IDENTIFY_DATA" | "IDENTIFY_MISSING_DATA" | "DEFINE_PROBLEM" | "SET_GOALS" | "ASSESS_MEDICATIONS" | "ASSESS_SAFETY" | "PROPOSE_DECISION" | "JUSTIFY" | "MONITOR" | "COMMUNICATE" | "CORRECT" | "TEACH_BACK" | "TRANSFER_CASE" | "COMPLETED";
export type ReactionType = "ALLERGY" | "INTOLERANCE" | "ADVERSE_EFFECT" | "UNKNOWN_REACTION";
export type DoseAssessmentStatus = "APPROPRIATE" | "POTENTIALLY_LOW" | "POTENTIALLY_HIGH" | "ADJUSTMENT_MAY_BE_REQUIRED" | "INSUFFICIENT_DATA" | "NO_EVIDENCE";
export type SafetySignalType = "ALLERGY_SIGNAL" | "INTERACTION_SIGNAL" | "CONTRAINDICATION_SIGNAL" | "DUPLICATION_SIGNAL" | "DOSE_SIGNAL" | "MONITORING_SIGNAL" | "MISSING_DATA_SIGNAL" | "RED_FLAG_SIGNAL";
export type ClinicalErrorType = "ERR_KNOW" | "ERR_MECH" | "ERR_CLIN" | "ERR_SAFE" | "ERR_CALC" | "ERR_READ" | "ERR_CONF" | "ERR_TIME" | "ERR_COMM" | "ERR_RAND";

export type MedicationExposure = Readonly<{ medicationName: string; activeIngredient: string; dose: number | null; doseUnit: string | null; route: string | null; frequency: string | null; indication: string | null; startDate?: string | null; duration?: string | null; status: "ACTIVE" | "STOPPED"; prn?: boolean; source: "SYNTHETIC_CASE" }>;
export type PatientReaction = Readonly<{ substance: string; type: ReactionType; description?: string | null }>;
export type PatientProfile = Readonly<{ synthetic: true; age?: number; sex?: string; weightKg?: number; heightCm?: number; pregnancyStatus?: string; allergies: readonly PatientReaction[]; diagnoses: readonly string[]; symptoms: readonly string[]; medications: readonly MedicationExposure[]; otc: readonly MedicationExposure[]; naturalHealthProducts: readonly MedicationExposure[]; adherence?: string; renalFunction?: Readonly<{ egfr?: number; crcl?: number }>; hepaticFunction?: Readonly<{ status?: string }>; vitalSigns: Readonly<Record<string, number>>; laboratoryValues: Readonly<Record<string, number>>; socialFactors: readonly string[]; previousMedicationReactions: readonly PatientReaction[]; treatmentGoals: readonly string[] }>;
export type ClinicalCase = Readonly<{ caseId: string; caseVersion: number; title: string; learningObjective: string; difficulty: "FOUNDATION" | "INTERMEDIATE" | "ADVANCED"; language: "fr" | "en"; patientProfile: PatientProfile; medications: readonly MedicationExposure[]; clinicalContext: string; expectedFindings: readonly string[]; expectedSafetySignals: readonly SafetySignalType[]; evidenceRequirements: readonly string[]; blueprintTags: readonly string[]; competencyTags: readonly string[]; provenance: "SYNTHETIC_FIXTURE" | "SYNTHETIC_GENERATED" }>;
export type SafetySignal = Readonly<{ signalId: string; signalType: SafetySignalType; severity: "LOW" | "MODERATE" | "HIGH" | null; description: string; relatedMedications: readonly string[]; requiredData: readonly string[]; evidenceRefs: readonly string[]; confidence: number; status: "CANDIDATE" | "CONFIRMED" | "NEEDS_VERIFICATION" }>;
export type MedicationReview = Readonly<{ indication: readonly string[]; effectiveness: readonly string[]; safety: readonly SafetySignal[]; adherence: readonly string[]; monitoring: readonly string[]; doseAssessments: readonly Readonly<{ medication: string; status: DoseAssessmentStatus; rationale: string; requiredData: readonly string[]; evidenceRefs: readonly string[] }>[] }>;
export type LearnerSignal = Readonly<{ objectiveId: string; result: "PASS" | "FAIL" | "PARTIAL"; confidence: number | null; durationMs: number; hintLevel: number; errorType: ClinicalErrorType | null; safetySignalMissed: boolean; teachBackResult: "PASS" | "NEEDS_REINFORCEMENT" | null; transferResult: "PASS" | "FAIL" | null }>;
export type CoachingSession = Readonly<{ sessionId: string; mode: CoachMode; objectiveId: string; learningObjective: string; language: "fr" | "en"; status: "ACTIVE" | "COMPLETED" | "FAILED"; currentStep: CoachingStep; learnerLevel: "FOUNDATION" | "INTERMEDIATE" | "ADVANCED"; startedAt: string; updatedAt: string; completedAt: string | null; sourceScope: readonly string[]; evidenceRefs: readonly string[]; currentCaseId: string | null; hintLevel: 0 | 1 | 2 | 3 | 4; attemptCount: number; learnerSignals: readonly LearnerSignal[]; learnerAnswers: readonly string[]; pendingTeachBack: boolean; sessionVersion: number }>;
