import { describe, expect, it, vi } from "vitest";
import type { CalculationAttempt, CalculationExerciseVersion, CalculationRetest } from "@/domain/calculations";
import type { CalculationsRepository } from "./calculations-ports";
import { GetCalculationExercise, PrepareCalculationRetest, SubmitCalculationAttempt } from "./calculations-use-cases";
const id = (n: number) => `10000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const exercise: CalculationExerciseVersion = { id: id(1), exerciseId: id(2), learningObjectiveId: id(3), version: 1, difficulty: "FOUNDATIONAL", inputs: [{ value: 1, unit: "g" }], steps: [{ position: 1, label: "fixture", expected: { value: 1000, unit: "mg" } }], expectedResult: { value: 1000, unit: "mg" }, dimension: "MASS", tolerance: 0.01, plausibility: { min: 900, max: 1100 }, status: "ACTIVE", createdAt: "2026-08-15T00:00:00.000Z" };
const setup = () => { let attempt: CalculationAttempt | null = null; let retest: CalculationRetest | null = null; const repository: CalculationsRepository = { findExerciseVersion: async (value) => value === exercise.id ? exercise : null, saveExerciseVersion: async () => undefined, saveAttempt: async (value) => { attempt=value; }, findAttempt: async () => attempt, listAttempts: async () => attempt ? [attempt] : [], saveRetest: async (value) => { retest=value; }, findRetest: async () => retest }; return { repository, logger: { event: vi.fn() }, ids: { next: vi.fn().mockReturnValueOnce(id(4)).mockReturnValueOnce(id(5)) }, clock: { now: () => "2026-08-15T01:00:00.000Z" } }; };
describe("Calculations application", () => {
  it("loads a versioned exercise with traceable logging", async () => { const c=setup(); expect(await new GetCalculationExercise(c.repository,c.logger).execute(exercise.id,"trace")).toBe(exercise); expect(c.logger.event).toHaveBeenCalledWith(expect.objectContaining({ name:"calculations.exercise_loaded",traceId:"trace" })); });
  it("persists a structured ERR-CALC result and critical remediation", async () => { const c=setup(); const result=await new SubmitCalculationAttempt(c.repository,c.ids,c.clock,c.logger).execute({ learnerId:id(6),exerciseVersionId:exercise.id,submission:{steps:[{value:1,unit:"L"}],result:{value:1,unit:"L"}},traceId:"trace" }); expect(result.evaluation).toMatchObject({ mastered:false,remediation:{required:true,priority:"CRITICAL"} }); });
  it("creates a traceable retest linked to an unsuccessful source attempt", async () => { const c=setup(); const submit=new SubmitCalculationAttempt(c.repository,c.ids,c.clock,c.logger); const attempt=await submit.execute({learnerId:id(6),exerciseVersionId:exercise.id,submission:{steps:[{value:2,unit:"mg"}],result:{value:2,unit:"mg"}},traceId:"t"}); const retest=await new PrepareCalculationRetest(c.repository,c.ids,c.clock,c.logger).execute({sourceAttemptId:attempt.id,exerciseVersionId:exercise.id,traceId:"t"}); expect(retest).toMatchObject({sourceAttemptId:attempt.id,resolved:false,resultAttemptId:null}); });
});
