import { describe, expect, it, vi } from "vitest";
import type { CalculationAttempt, CalculationExerciseVersion, CalculationRetest } from "@/domain/calculations";
import type { CalculationsRepository } from "./calculations-ports";
import { CompleteCalculationRetest, GetCalculationExercise, PrepareCalculationRetest, SubmitCalculationAttempt } from "./calculations-use-cases";
const id=(n:number)=>`10000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const exercise=(version:number):CalculationExerciseVersion=>({id:id(version),exerciseId:id(20),learningObjectiveId:id(30),version,difficulty:"FOUNDATIONAL",inputs:[{value:1,unit:"g"}],steps:[{position:1,label:"fixture",expected:{value:1000,unit:"mg"}}],expectedResult:{value:1000,unit:"mg"},dimension:"MASS",tolerance:0.01,plausibility:{min:900,max:1100},status:"ACTIVE",createdAt:"2026-08-15T00:00:00.000Z"});
const setup=()=>{const attempts=new Map<string,CalculationAttempt>();const retests=new Map<string,CalculationRetest>();const repository:CalculationsRepository={findExerciseVersion:async value=>[exercise(1),exercise(2)].find(item=>item.id===value)??null,saveExerciseVersion:async()=>undefined,saveAttempt:async value=>{attempts.set(value.id,value);},findAttempt:async value=>attempts.get(value)??null,listAttempts:async()=>[...attempts.values()],saveRetest:async value=>{retests.set(value.id,value);},findRetest:async value=>retests.get(value)??null};let sequence=40;return{repository,logger:{event:vi.fn()},ids:{next:()=>id(sequence++)},clock:{now:()=>"2026-08-15T01:00:00.000Z"},attempts,retests};};
describe("Calculations application",()=>{
  it("loads a versioned exercise with traceable logging",async()=>{const c=setup();expect(await new GetCalculationExercise(c.repository,c.logger).execute(id(1),"trace")).toMatchObject({version:1});});
  it("generates distinct stable UUID observation IDs",async()=>{const c=setup();const result=await new SubmitCalculationAttempt(c.repository,c.ids,c.clock,c.logger).execute({learnerId:id(60),exerciseVersionId:id(1),submission:{steps:[{value:1,unit:"L"}],result:{value:1,unit:"L"}},traceId:"trace"});expect(result.observations.length).toBeGreaterThan(1);expect(new Set(result.observations.map(item=>item.id)).size).toBe(result.observations.length);for(const item of result.observations)expect(item.id).toMatch(/^[0-9a-f-]{36}$/);});
  it("rejects the same instance and accepts a distinct retest variant",async()=>{const c=setup();const submit=new SubmitCalculationAttempt(c.repository,c.ids,c.clock,c.logger);const source=await submit.execute({learnerId:id(60),exerciseVersionId:id(1),submission:{steps:[{value:2,unit:"mg"}],result:{value:2,unit:"mg"}},traceId:"t"});const prepare=new PrepareCalculationRetest(c.repository,c.ids,c.clock,c.logger);await expect(prepare.execute({sourceAttemptId:source.id,exerciseVersionId:id(1),traceId:"t"})).rejects.toMatchObject({code:"CALCULATION_RETEST_INVALID"});expect(await prepare.execute({sourceAttemptId:source.id,exerciseVersionId:id(2),traceId:"t"})).toMatchObject({sourceExerciseVersionId:id(1),retestExerciseVersionId:id(2),reason:"ARITHMETIC",resolved:false});});
  it.each([[1000,true],[2,false]])("persists retest result and resolution while retaining source error (value=%s)",async(value,resolved)=>{const c=setup();const submit=new SubmitCalculationAttempt(c.repository,c.ids,c.clock,c.logger);const source=await submit.execute({learnerId:id(60),exerciseVersionId:id(1),submission:{steps:[{value:2,unit:"mg"}],result:{value:2,unit:"mg"}},traceId:"t"});const retest=await new PrepareCalculationRetest(c.repository,c.ids,c.clock,c.logger).execute({sourceAttemptId:source.id,exerciseVersionId:id(2),traceId:"t"});const result=await submit.execute({learnerId:id(60),exerciseVersionId:id(2),submission:{steps:[{value,unit:"mg"}],result:{value,unit:"mg"}},traceId:"t"});const completed=await new CompleteCalculationRetest(c.repository,c.clock,c.logger).execute({retestId:retest.id,resultAttemptId:result.id,traceId:"t"});expect(completed).toMatchObject({resultAttemptId:result.id,resolved,completedAt:"2026-08-15T01:00:00.000Z"});expect((await c.repository.findAttempt(source.id))?.observations[0]?.category).toBe("ARITHMETIC");});
});
